/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Usuario
 */
public class LoginDoctor extends javax.swing.JFrame {

    /**
     * Creates new form Ingresar_Jugadores
     */
    public LoginDoctor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Boton_Ingresar = new javax.swing.JButton();
        Cuadro_Email = new javax.swing.JTextField();
        Cuadro_Direccion = new javax.swing.JTextField();
        Cuadro_Telefono = new javax.swing.JTextField();
        Cuadro_Cedula = new javax.swing.JTextField();
        Cuadro_Nombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Item_Volver = new javax.swing.JMenu();
        Boton_Volver = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Boton_Ingresar.setBackground(new java.awt.Color(255, 255, 0));
        Boton_Ingresar.setFont(new java.awt.Font("Khmer UI", 1, 24)); // NOI18N
        Boton_Ingresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/DOCTOR.png"))); // NOI18N
        Boton_Ingresar.setText("INGRESAR");
        getContentPane().add(Boton_Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 510, -1, -1));

        Cuadro_Email.setBackground(new java.awt.Color(204, 204, 255));
        Cuadro_Email.setFont(new java.awt.Font("Khmer UI", 1, 24)); // NOI18N
        Cuadro_Email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Cuadro_EmailKeyTyped(evt);
            }
        });
        getContentPane().add(Cuadro_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 380, 40));

        Cuadro_Direccion.setBackground(new java.awt.Color(204, 204, 255));
        Cuadro_Direccion.setFont(new java.awt.Font("Khmer UI", 1, 24)); // NOI18N
        Cuadro_Direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Cuadro_DireccionKeyTyped(evt);
            }
        });
        getContentPane().add(Cuadro_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 350, 40));

        Cuadro_Telefono.setBackground(new java.awt.Color(204, 204, 255));
        Cuadro_Telefono.setFont(new java.awt.Font("Khmer UI", 1, 24)); // NOI18N
        Cuadro_Telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Cuadro_TelefonoKeyTyped(evt);
            }
        });
        getContentPane().add(Cuadro_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 380, 40));

        Cuadro_Cedula.setBackground(new java.awt.Color(204, 204, 255));
        Cuadro_Cedula.setFont(new java.awt.Font("Khmer UI", 1, 24)); // NOI18N
        Cuadro_Cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Cuadro_CedulaKeyTyped(evt);
            }
        });
        getContentPane().add(Cuadro_Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 380, 40));

        Cuadro_Nombre.setBackground(new java.awt.Color(204, 204, 255));
        Cuadro_Nombre.setFont(new java.awt.Font("Khmer UI", 1, 24)); // NOI18N
        Cuadro_Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Cuadro_NombreKeyTyped(evt);
            }
        });
        getContentPane().add(Cuadro_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 400, 40));

        jLabel9.setFont(new java.awt.Font("Khmer UI", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CEDULA:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 190, -1));

        jLabel6.setFont(new java.awt.Font("Khmer UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("EMAIL:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 150, -1));

        jLabel5.setFont(new java.awt.Font("Khmer UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DIRECCIÓN:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 240, -1));

        jLabel4.setFont(new java.awt.Font("Khmer UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TELEFONO:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 230, -1));

        jLabel3.setFont(new java.awt.Font("Khmer UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NOMBRE:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 210, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Main.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Doctor.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1000, 630));

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));

        Item_Volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Volver.png"))); // NOI18N
        Item_Volver.setText("VOLVER");

        Boton_Volver.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        Boton_Volver.setText("VOLVER MENU");
        Boton_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_VolverActionPerformed(evt);
            }
        });
        Item_Volver.add(Boton_Volver);

        jMenuBar1.add(Item_Volver);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_VolverActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_Boton_VolverActionPerformed

    private void Cuadro_NombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Cuadro_NombreKeyTyped
        // TODO add your handling code here:
        char v;
        
        v=evt.getKeyChar();
        
        if((v<'A' || v>'Z') && (v<' ' || v>' ')){
            
            evt.consume();
        }
        
    }//GEN-LAST:event_Cuadro_NombreKeyTyped

    private void Cuadro_CedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Cuadro_CedulaKeyTyped
        // TODO add your handling code here:
        
        char v;
        
        v=evt.getKeyChar();
        
        if((v<'0' || v>'9')){
            
            evt.consume();
        }
    }//GEN-LAST:event_Cuadro_CedulaKeyTyped

    private void Cuadro_TelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Cuadro_TelefonoKeyTyped
        // TODO add your handling code here:
        char v;
        
        v=evt.getKeyChar();
        
        if((v<'1' || v>'9')){
            
            evt.consume();
        }
    }//GEN-LAST:event_Cuadro_TelefonoKeyTyped

    private void Cuadro_DireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Cuadro_DireccionKeyTyped
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_Cuadro_DireccionKeyTyped

    private void Cuadro_EmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Cuadro_EmailKeyTyped
        // TODO add your handling code here:
             
      
    }//GEN-LAST:event_Cuadro_EmailKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginDoctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Boton_Ingresar;
    public javax.swing.JMenuItem Boton_Volver;
    public javax.swing.JTextField Cuadro_Cedula;
    public javax.swing.JTextField Cuadro_Direccion;
    public javax.swing.JTextField Cuadro_Email;
    public javax.swing.JTextField Cuadro_Nombre;
    public javax.swing.JTextField Cuadro_Telefono;
    private javax.swing.JMenu Item_Volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
