/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author DAVIER BOLAÑOS
 */
public class MainLogin extends javax.swing.JFrame {

    /**
     * Creates new form MainLogin
     */
    public MainLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Boton_PACIENTE = new javax.swing.JButton();
        Boton_FARMACEUTA = new javax.swing.JButton();
        Boton_DOCTOR = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 625));
        setMinimumSize(new java.awt.Dimension(1000, 625));
        setPreferredSize(new java.awt.Dimension(1000, 625));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Boton_PACIENTE.setBackground(new java.awt.Color(0, 0, 0));
        Boton_PACIENTE.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        Boton_PACIENTE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PACIENTE.png"))); // NOI18N
        Boton_PACIENTE.setText("PACIENTE");
        Boton_PACIENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_PACIENTEActionPerformed(evt);
            }
        });
        getContentPane().add(Boton_PACIENTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, 260, 80));

        Boton_FARMACEUTA.setBackground(new java.awt.Color(0, 0, 0));
        Boton_FARMACEUTA.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        Boton_FARMACEUTA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FARMACEUTA.png"))); // NOI18N
        Boton_FARMACEUTA.setText("FARMACEUTA");
        Boton_FARMACEUTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_FARMACEUTAActionPerformed(evt);
            }
        });
        getContentPane().add(Boton_FARMACEUTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 260, 80));

        Boton_DOCTOR.setBackground(new java.awt.Color(0, 0, 0));
        Boton_DOCTOR.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        Boton_DOCTOR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/DOCTOR.png"))); // NOI18N
        Boton_DOCTOR.setText("DOCTOR");
        Boton_DOCTOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_DOCTORActionPerformed(evt);
            }
        });
        getContentPane().add(Boton_DOCTOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 260, 80));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Main.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_DOCTORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_DOCTORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_DOCTORActionPerformed

    private void Boton_FARMACEUTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_FARMACEUTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_FARMACEUTAActionPerformed

    private void Boton_PACIENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_PACIENTEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_PACIENTEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Boton_DOCTOR;
    public javax.swing.JButton Boton_FARMACEUTA;
    public javax.swing.JButton Boton_PACIENTE;
    private javax.swing.JLabel Fondo;
    // End of variables declaration//GEN-END:variables
}
